[package]
name = "twsorter-benchmark"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
twsorter = { path = "../twsorter" }
